#!/bin/bash

sed -i "s/<SEC_FLOATING_FEATURE_COMMON_CONFIG_EDGE><\/SEC_FLOATING_FEATURE_COMMON_CONFIG_EDGE>/<SEC_FLOATING_FEATURE_COMMON_CONFIG_EDGE>people,task,circle,panel,-nightclock<\/SEC_FLOATING_FEATURE_COMMON_CONFIG_EDGE>/" etc/floating_feature.xml
sed -i "s/<SEC_FLOATING_FEATURE_FRAMEWORK_CONFIG_TASK_EDGE_EMBEDDED_ITEM><\/SEC_FLOATING_FEATURE_FRAMEWORK_CONFIG_TASK_EDGE_EMBEDDED_ITEM>/<SEC_FLOATING_FEATURE_FRAMEWORK_CONFIG_TASK_EDGE_EMBEDDED_ITEM>panorama<\/SEC_FLOATING_FEATURE_FRAMEWORK_CONFIG_TASK_EDGE_EMBEDDED_ITEM>/" etc/floating_feature.xml
sed -i "s/<SEC_FLOATING_FEATURE_MESSAGE_SUPPORT_SPLIT_MODE>FALSE<\/SEC_FLOATING_FEATURE_MESSAGE_SUPPORT_SPLIT_MODE>/<SEC_FLOATING_FEATURE_MESSAGE_SUPPORT_SPLIT_MODE>TRUE<\/SEC_FLOATING_FEATURE_MESSAGE_SUPPORT_SPLIT_MODE>/" etc/floating_feature.xml
